name: Build Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm --help
            yarn --version
            pm2 --version
            cd ${{ secrets.PROJECT_DIR }}
            git fetch origin main
            git reset --hard
            git pull origin main
            yarn install
            yarn build
            pm2 restart ${{ secrets.PM2_APP_NAME }}
            echo "Deployment and build successful."
